name: Publish app

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Publish docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/rikudousage/gitlab-ce-forced-approvals
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=dev
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  publish_binary:
    runs-on: ubuntu-latest
    name: Publish binary
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile binary
        env:
          CGO_ENABLED: 0
        run: go build -o gitlab-ce-forced-approvals .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: gitlab-ce-forced-approvals

  create_release:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Create a release
    needs:
      - publish_binary
      - publish_docker
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Extract Version Name
        id: extract_name
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return context.payload.ref.replace('refs/tags/v', '');
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.extract_name.outputs.result }}
          draft: false
          prerelease: false
          body: |
            You can download `gitlab-ce-forced-approvals` below for x86 Linux or use the docker image
            `ghcr.io/rikudousage/gitlab-ce-forced-approvals:${{ steps.extract_name.outputs.result }}`.
          files: |
            gitlab-ce-forced-approvals

